name: CI

on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        shell: bash
        env:
          VAR1: "abc"
          VAR2: "def"
        run: |
          echo "Target branch: ${{ github.event.pull_request.head.ref }}"
          echo "var1: $VAR1"
          echo "SECRET: ${{ secrets.SECRET | hash }}"
