name: CI

on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        shell: bash
        env:
          VAR1: "abc"
        run: |
          echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          echo "$VAR1"
